env:
  node: true
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'airbnb-typescript'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
  - import
rules:
  import/extensions: 0
  react/prop-types: 0
  indent: ['error', 2]
  react/jsx-indent: ['error', 2]
  react/jsx-indent-props: ['error', 2]
  react/react-in-jsx-scope: 0
  functional/no-conditional-statements: 0
  functional/no-expression-statements: 0
  functional/functional-parameters: 0
  no-multi-spaces: 'error'
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]